POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My first post",
  "postType": "post",
  "slug": "my-first-post-6",
  "status": "draft",
  "content": "This is the content of my first post",
  "schema": "{}",
  "featuredImageUrl": "https://www.example.com/featured-image.jpg",
  "publishOn": "2024-03-16T07:46:32+0000",
  "tags": [1, 3],
  "metaOptions": {
    "metaValue": "{ \"sideBarEnable\": true }"
  },
  "authorId": 1
}