POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJlbWFpbCI6ImpvaG5AZG9lMTAuY29tIiwiaWF0IjoxNzI4MTg3OTAyLCJleHAiOjE3MjgxOTE1MDIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.8EELh7hB5D295AlC5YatzyMJFLmsTlZDZdHYCRlRuek

{
  "title": "My first post",
  "postType": "post",
  "slug": "my-first-post-22",
  "status": "draft",
  "content": "This is the content of my first post",
  "schema": "{}",
  "featuredImageUrl": "https://www.example.com/featured-image.jpg",
  "publishOn": "2024-10-02",
  "tags": [1],
  "metaOptions": {
    "metaValue": "{ \"sideBarEnable\": true }"
  }
}