POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@doe2.com",
  "password": "@Lehung2002"
}



POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJlbWFpbCI6ImpvaG5AZG9lMTAuY29tIiwiaWF0IjoxNzI4MTM4ODkwLCJleHAiOjE3MjgxNDI0OTAsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.7OSq8FDHTenY1axF8_LK876Ua9ZcBq19qjvKSTvjGXc

{
  "users": [
    {
    "firstName": "John1",
    "lastName": "Doe1",
    "email": "john@doe12.com",
    "password": "@Lehung2002"
    }
  ]
}